[package]
name = "cipher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto="0.2.0"
hex="0.4.3"
base64="0.13.0"
rustc-serialize = "0.3"
rand = "0.7"
openssl="0.10"
