[package]
name = "proof_of_work"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = "0.10"
chrono = "0.4"
rand = "0.7"
hex="0.4.3"